# Generated by Django 6.0.2 on 2026-02-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='categoria',
            field=models.CharField(choices=[('projeto de trabalho', 'Projeto de trbalho'), ('estudos', 'Estudos'), ('pessoal', 'Pessoal')], default='Projeto de Trabalho', max_length=50),
        ),
    ]
