# Generated by Django 6.0.2 on 2026-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data',
            new_name='data_entrega',
        ),
        migrations.AddField(
            model_name='task',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='link_localizacao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='categoria',
            field=models.CharField(choices=[('trabalho', 'Trabalho'), ('estudos', 'Estudos'), ('pessoal', 'Pessoal'), ('importante', 'Importante')], default='trabalho', max_length=50),
        ),
    ]
