# Generated by Django 6.0.2 on 2026-02-27 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_data_task_data_entrega_task_importante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='importante',
        ),
        migrations.RemoveField(
            model_name='task',
            name='link_localizacao',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='task',
            name='categoria',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente')], default='concluido', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_entrega',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date de Término'),
        ),
    ]
